[simulation]
calculate_gradients = true 

[visualization]
export = true
interval = 1
	[[visualize_agent]]
	name = "platelet"
	additional_data_members = [ "cell_color_" ]
	
	[[visualize_agent]]
	name = "epithelial_cell"
	additional_data_members = [ "cell_color_" ]
	
	[[visualize_agent]]
	name = "macrophage"
	additional_data_members = [ "cell_color_" ]
	
	[[visualize_agent]]
	name = "keratinocyte"
	additional_data_members = [ "cell_color_" ]
	
	[[visualize_agent]]
	name = "fibroblast"
	additional_data_members = [ "cell_color_" ]
	
	#[[visualize_diffusion]]
	#name = "PDGF"
	
